import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // ─── Learning Paths ────────────────────────────────────────────────────────
  paths: [
    {
      type: 'category',
      label: '🗺️ Learning Paths',
      collapsible: false,
      items: [
        'paths/beginner',
        'paths/python_developer',
        'paths/frontend_developer',
        'paths/backend_developer',
        'paths/fullstack',
        'paths/systems',
        'paths/devops',
        'paths/ai_engineer',
      ],
    },
  ],

  // ─── Courses ───────────────────────────────────────────────────────────────
  courses: [
    'courses/index',
    {
      type: 'category',
      label: 'Python Fundamentals',
      link: { type: 'doc', id: 'courses/python_fundamentals/index' },
      items: [
        'courses/python_fundamentals/lesson_01',
        'courses/python_fundamentals/lesson_02',
        'courses/python_fundamentals/lesson_03',
        'courses/python_fundamentals/lesson_04',
        'courses/python_fundamentals/lesson_05',
        'courses/python_fundamentals/lesson_06',
      ],
    },
    {
      type: 'category',
      label: 'Python: Data and Files',
      link: { type: 'doc', id: 'courses/python_data_and_files/index' },
      items: [
        'courses/python_data_and_files/lesson_01',
        'courses/python_data_and_files/lesson_02',
        'courses/python_data_and_files/lesson_03',
        'courses/python_data_and_files/lesson_04',
      ],
    },
    {
      type: 'category',
      label: 'Python: OOP',
      link: { type: 'doc', id: 'courses/python_oop/index' },
      items: [
        'courses/python_oop/lesson_01',
        'courses/python_oop/lesson_02',
        'courses/python_oop/lesson_03',
        'courses/python_oop/lesson_04',
        'courses/python_oop/lesson_05',
      ],
    },
    {
      type: 'category',
      label: 'Python: Professional Tools',
      link: { type: 'doc', id: 'courses/python_professional/index' },
      items: [
        'courses/python_professional/lesson_01',
        'courses/python_professional/lesson_02',
      ],
    },
    {
      type: 'category',
      label: 'HTML Fundamentals',
      link: { type: 'doc', id: 'courses/html_fundamentals/index' },
      items: [
        'courses/html_fundamentals/lesson_01',
        'courses/html_fundamentals/lesson_02',
        'courses/html_fundamentals/lesson_03',
        'courses/html_fundamentals/lesson_04',
        'courses/html_fundamentals/lesson_05',
        'courses/html_fundamentals/lesson_06',
        'courses/html_fundamentals/lesson_07',
        'courses/html_fundamentals/lesson_08',
      ],
    },
    {
      type: 'category',
      label: 'CSS Fundamentals',
      link: { type: 'doc', id: 'courses/css_fundamentals/index' },
      items: [
        'courses/css_fundamentals/lesson_01',
        'courses/css_fundamentals/lesson_02',
        'courses/css_fundamentals/lesson_03',
        'courses/css_fundamentals/lesson_04',
        'courses/css_fundamentals/lesson_05',
        'courses/css_fundamentals/lesson_06',
        'courses/css_fundamentals/lesson_07',
        'courses/css_fundamentals/lesson_08',
        'courses/css_fundamentals/lesson_09',
      ],
    },
    {
      type: 'category',
      label: 'Vanilla JavaScript Fundamentals',
      link: { type: 'doc', id: 'courses/javascript_fundamentals/index' },
      items: [
        'courses/javascript_fundamentals/lesson_01',
        'courses/javascript_fundamentals/lesson_02',
        'courses/javascript_fundamentals/lesson_03',
        'courses/javascript_fundamentals/lesson_04',
        'courses/javascript_fundamentals/lesson_05',
        'courses/javascript_fundamentals/lesson_06',
        'courses/javascript_fundamentals/lesson_07',
        'courses/javascript_fundamentals/lesson_08',
        'courses/javascript_fundamentals/lesson_09',
      ],
    },
    {
      type: 'category',
      label: 'Build Tools & Toolchain',
      link: { type: 'doc', id: 'courses/build_tools/index' },
      items: [
        'courses/build_tools/lesson_01',
        'courses/build_tools/lesson_02',
        'courses/build_tools/lesson_03',
        'courses/build_tools/lesson_04',
        'courses/build_tools/lesson_05',
      ],
    },
    {
      type: 'category',
      label: 'TypeScript Fundamentals',
      link: { type: 'doc', id: 'courses/typescript_fundamentals/index' },
      items: [
        'courses/typescript_fundamentals/lesson_01',
        'courses/typescript_fundamentals/lesson_02',
        'courses/typescript_fundamentals/lesson_03',
        'courses/typescript_fundamentals/lesson_04',
        'courses/typescript_fundamentals/lesson_05',
        'courses/typescript_fundamentals/lesson_06',
        'courses/typescript_fundamentals/lesson_07',
      ],
    },
    {
      type: 'category',
      label: 'Tailwind CSS',
      link: { type: 'doc', id: 'courses/tailwind_css/index' },
      items: [
        'courses/tailwind_css/lesson_01',
        'courses/tailwind_css/lesson_02',
        'courses/tailwind_css/lesson_03',
        'courses/tailwind_css/lesson_04',
        'courses/tailwind_css/lesson_05',
        'courses/tailwind_css/lesson_06',
        'courses/tailwind_css/lesson_07',
        'courses/tailwind_css/lesson_08',
      ],
    },
    {
      type: 'category',
      label: 'React Fundamentals',
      link: { type: 'doc', id: 'courses/react_fundamentals/index' },
      items: [
        'courses/react_fundamentals/lesson_01',
        'courses/react_fundamentals/lesson_02',
        'courses/react_fundamentals/lesson_03',
        'courses/react_fundamentals/lesson_04',
        'courses/react_fundamentals/lesson_05',
        'courses/react_fundamentals/lesson_06',
        'courses/react_fundamentals/lesson_07',
        'courses/react_fundamentals/lesson_08',
        'courses/react_fundamentals/lesson_09',
      ],
    },
    {
      type: 'category',
      label: 'React Advanced',
      link: { type: 'doc', id: 'courses/react_advanced/index' },
      items: [
        'courses/react_advanced/lesson_01',
        'courses/react_advanced/lesson_02',
        'courses/react_advanced/lesson_03',
        'courses/react_advanced/lesson_04',
        'courses/react_advanced/lesson_05',
        'courses/react_advanced/lesson_06',
        'courses/react_advanced/lesson_07',
      ],
    },
    {
      type: 'category',
      label: 'Next.js',
      link: { type: 'doc', id: 'courses/nextjs/index' },
      items: [
        'courses/nextjs/lesson_01',
        'courses/nextjs/lesson_02',
        'courses/nextjs/lesson_03',
        'courses/nextjs/lesson_04',
        'courses/nextjs/lesson_05',
        'courses/nextjs/lesson_06',
        'courses/nextjs/lesson_07',
        'courses/nextjs/lesson_08',
      ],
    },
    {
      type: 'category',
      label: 'Angular Fundamentals',
      link: { type: 'doc', id: 'courses/angular_fundamentals/index' },
      items: [
        'courses/angular_fundamentals/lesson_01',
        'courses/angular_fundamentals/lesson_02',
        'courses/angular_fundamentals/lesson_03',
        'courses/angular_fundamentals/lesson_04',
        'courses/angular_fundamentals/lesson_05',
        'courses/angular_fundamentals/lesson_06',
        'courses/angular_fundamentals/lesson_07',
        'courses/angular_fundamentals/lesson_08',
        'courses/angular_fundamentals/lesson_09',
      ],
    },
    {
      type: 'category',
      label: 'Node.js Fundamentals',
      link: { type: 'doc', id: 'courses/nodejs_fundamentals/index' },
      items: [
        'courses/nodejs_fundamentals/lesson_01',
        'courses/nodejs_fundamentals/lesson_02',
        'courses/nodejs_fundamentals/lesson_03',
        'courses/nodejs_fundamentals/lesson_04',
        'courses/nodejs_fundamentals/lesson_05',
        'courses/nodejs_fundamentals/lesson_06',
        'courses/nodejs_fundamentals/lesson_07',
      ],
    },
    {
      type: 'category',
      label: 'Express API',
      link: { type: 'doc', id: 'courses/express_api/index' },
      items: [
        'courses/express_api/lesson_01',
        'courses/express_api/lesson_02',
        'courses/express_api/lesson_03',
        'courses/express_api/lesson_04',
        'courses/express_api/lesson_05',
        'courses/express_api/lesson_06',
        'courses/express_api/lesson_07',
        'courses/express_api/lesson_08',
      ],
    },
    {
      type: 'category',
      label: 'PHP & Server-Side Rendering',
      link: { type: 'doc', id: 'courses/php_ssr/index' },
      items: [
        'courses/php_ssr/lesson_01',
        'courses/php_ssr/lesson_02',
        'courses/php_ssr/lesson_03',
        'courses/php_ssr/lesson_04',
        'courses/php_ssr/lesson_05',
        'courses/php_ssr/lesson_06',
        'courses/php_ssr/lesson_07',
      ],
    },
    {
      type: 'category',
      label: 'Laravel Fundamentals',
      link: { type: 'doc', id: 'courses/laravel_fundamentals/index' },
      items: [
        'courses/laravel_fundamentals/lesson_01',
        'courses/laravel_fundamentals/lesson_02',
        'courses/laravel_fundamentals/lesson_03',
        'courses/laravel_fundamentals/lesson_04',
        'courses/laravel_fundamentals/lesson_05',
        'courses/laravel_fundamentals/lesson_06',
        'courses/laravel_fundamentals/lesson_07',
      ],
    },
  ],

  // ─── Wiki / Reference ──────────────────────────────────────────────────────
  wiki: [
    {
      type: 'category',
      label: 'Foundations',
      link: { type: 'doc', id: 'domains/foundations/index' },
      items: [
        'domains/foundations/programming_basics',
        'domains/foundations/data_structures',
        {
          type: 'category',
          label: 'Algorithms',
          link: { type: 'doc', id: 'domains/foundations/algorithms/index' },
          items: [
            'domains/foundations/algorithms/complexity',
            'domains/foundations/algorithms/search',
            'domains/foundations/algorithms/sorting',
            'domains/foundations/algorithms/recursion',
            'domains/foundations/algorithms/graph',
            'domains/foundations/algorithms/pathfinding',
            'domains/foundations/algorithms/greedy',
            'domains/foundations/algorithms/backtracking',
            'domains/foundations/algorithms/string',
            'domains/foundations/algorithms/vectors',
          ],
        },
        'domains/foundations/regex',
        {
          type: 'category',
          label: 'Protocols & Standards',
          link: { type: 'doc', id: 'domains/foundations/protocols_and_standards/index' },
          items: [
            'domains/foundations/protocols_and_standards/osi_model',
            'domains/foundations/protocols_and_standards/tcp_ip',
            'domains/foundations/protocols_and_standards/quic',
            'domains/foundations/protocols_and_standards/tls',
            'domains/foundations/protocols_and_standards/oauth',
            'domains/foundations/protocols_and_standards/ssh',
            'domains/foundations/protocols_and_standards/dns',
            'domains/foundations/protocols_and_standards/http',
            'domains/foundations/protocols_and_standards/rest',
            'domains/foundations/protocols_and_standards/websockets',
            'domains/foundations/protocols_and_standards/rpc',
            'domains/foundations/protocols_and_standards/email_protocols',
            'domains/foundations/protocols_and_standards/messaging_protocols',
            'domains/foundations/protocols_and_standards/standards_bodies',
          ],
        },
        'domains/foundations/hardware_fundamentals',
        'domains/foundations/memory_management',
        'domains/foundations/concurrency',
        'domains/foundations/networking',
        'domains/foundations/os_concepts',
      ],
    },
    {
      type: 'category',
      label: 'Web Development',
      link: { type: 'doc', id: 'domains/web_dev/index' },
      items: [
        'domains/web_dev/html_css',
        'domains/web_dev/javascript_core',
        'domains/web_dev/typescript',
        'domains/web_dev/frontend_frameworks',
        'domains/web_dev/nodejs',
        'domains/web_dev/http_server',
        'domains/web_dev/rest_api',
        'domains/web_dev/graphql',
        'domains/web_dev/ssr_csr',
      ],
    },
    {
      type: 'category',
      label: 'Systems Programming',
      link: { type: 'doc', id: 'domains/systems_programming/index' },
      items: [
        'domains/systems_programming/c_fundamentals',
        'domains/systems_programming/rust_fundamentals',
        'domains/systems_programming/rust_advanced',
        'domains/systems_programming/assembly_basics',
      ],
    },
    {
      type: 'category',
      label: 'DevOps',
      link: { type: 'doc', id: 'domains/devops/index' },
      items: [
        'domains/devops/linux_cli',
        'domains/devops/git_workflow',
        'domains/devops/docker',
        'domains/devops/kubernetes',
        'domains/devops/ci_cd',
        'domains/devops/iac',
        'domains/devops/monitoring',
        'domains/devops/testing',
      ],
    },
    {
      type: 'category',
      label: 'Databases',
      link: { type: 'doc', id: 'domains/databases/index' },
      items: [
        'domains/databases/sql_fundamentals',
        'domains/databases/nosql',
        'domains/databases/design',
        'domains/databases/performance',
      ],
    },
    {
      type: 'category',
      label: 'Cloud',
      link: { type: 'doc', id: 'domains/cloud/index' },
      items: [
        'domains/cloud/fundamentals',
        'domains/cloud/serverless',
        'domains/cloud/architecture_patterns',
      ],
    },
    {
      type: 'category',
      label: 'AI / ML',
      link: { type: 'doc', id: 'domains/ai_ml/index' },
      items: [
        'domains/ai_ml/foundations',
        'domains/ai_ml/llm_engineering',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      link: { type: 'doc', id: 'domains/security/index' },
      items: [
        'domains/security/appsec',
      ],
    },
  ],

  // ─── Projects ──────────────────────────────────────────────────────────────
  projects: [
    'projects/index',
    'projects/p01_cli_tool',
    'projects/p02_rest_api',
    'projects/p03_fullstack_app',
    'projects/p04_containerized_service',
    'projects/p05_data_pipeline',
    'projects/p06_ai_agent',
    'projects/p07_devops_pipeline',
  ],
};

export default sidebars;
